default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres@localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: paapi_development

test:
  <<: *default
  database: paapi_test

production:
  <<: *default
  database: paapi_production
