---
name: Verify

on:
  workflow_call:
    inputs:
      bundler-audit:
        type: boolean
        default: false
      brakeman:
        type: boolean
        default: false
      rubocop:
        type: boolean
        default: false

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Check bundle for known CVEs
        if: ${{ inputs.bundler-audit == true }}
        run: |
          bundle exec bundler-audit

      - name: Analyse code for vulnerabilities
        if: ${{ inputs.brakeman == true }}
        run: |
          bundle exec brakeman

      - name: Analyse code for formatting
        if: ${{ inputs.rubocop == true }}
        run: |
          ${{ inputs.run-before-linters }}
          bundle exec rubocop
